package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/google/go-jsonnet"
)

// Per-service, like values.yaml -- not per-team. See dashboard.go's history
// (main.go / gitops README) for why: a team's services spread across many
// repos have no natural single owner for one shared file. A team-wide
// rollup dashboard, if a team wants one, is a deliberately-built, separate
// artifact in the platform's own observability-dashboards repo -- not
// auto-generated here.
//
// The actual dashboard JSON is generated by evaluating a Jsonnet function
// (not a Go text/template -- Jsonnet's syntax doesn't collide with
// Grafana's own {{ }} dashboard variables, so no escaping hack is needed).
// That Jsonnet source is NOT embedded in this binary (no go:embed) -- it's
// read from spec.DashboardTemplatePath at runtime. The canonical copy lives
// in the observability-dashboards repo (templates/standard-microservice-
// template.jsonnet), the one place a human edits it; a go:embed'd copy in
// this repo would just be a second copy that silently drifts from that one.
// .gitlab-ci.yml's generate job fetches it fresh from there before this
// runs -- see that file's comment on why real-time fetch was chosen over
// vendoring a copy here.
func writeDashboard(spec ServiceSpec, outDir string) error {
	dashDir := filepath.Join(outDir, "dashboards")
	if err := os.MkdirAll(dashDir, 0o755); err != nil {
		return err
	}

	dashboardJSON, err := evalDashboardJsonnet(spec)
	if err != nil {
		return fmt.Errorf("evaluating dashboard template: %w", err)
	}

	configMap := fmt.Sprintf(`apiVersion: v1
kind: ConfigMap
metadata:
  name: %s-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  %s.json: |
%s
`, spec.Name, spec.Name, indentLines(dashboardJSON, "    "))

	path := filepath.Join(dashDir, spec.Name+"-dashboard.yaml")
	if err := os.WriteFile(path, []byte(configMap), 0o644); err != nil {
		return err
	}

	fmt.Println("wrote", path)
	return nil
}

// evalDashboardJsonnet reads spec.DashboardTemplatePath and calls its
// top-level function with this service's real values, returning
// pretty-printed JSON. The Jsonnet VM's Importer only needs to resolve
// the one file already read into memory -- there's no on-disk `import`
// chain to support here.
func evalDashboardJsonnet(spec ServiceSpec) (string, error) {
	src, err := os.ReadFile(spec.DashboardTemplatePath)
	if err != nil {
		return "", fmt.Errorf(
			"reading %s: %w (in CI this is fetched from the observability-dashboards "+
				"repo before generate runs; for a local run, pass --dashboard-template "+
				"pointing at a local checkout of that repo's templates/standard-microservice-template.jsonnet)",
			spec.DashboardTemplatePath, err,
		)
	}

	vm := jsonnet.MakeVM()
	vm.Importer(&jsonnet.MemoryImporter{
		Data: map[string]jsonnet.Contents{
			"dashboard.jsonnet": jsonnet.MakeContents(string(src)),
		},
	})

	snippet := fmt.Sprintf(
		`(import "dashboard.jsonnet")(name=%q, team=%q, hasHPA=%v)`,
		spec.Name, spec.Team, spec.HasHPA,
	)

	return vm.EvaluateAnonymousSnippet("dashboard-call.jsonnet", snippet)
}

func indentLines(s, prefix string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, line := range lines {
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n")
}
